apiVersion: v1
kind: Namespace
metadata:
  name: microservices
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: app-services
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: ingress-nginx


