apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
 name: auth-plugin          # Must match name in Ingress annotation
 namespace: microservices
 annotations:
  kubernetes.io/ingress.class: kong
config:
 key_names:
   - apikey                        # Header name for the API key
 hide_credentials: true
plugin: key-auth
