apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
 name: ratelimit-plugin    # Must match name in Ingress annotation
 namespace: microservices
 annotations:
  kubernetes.io/ingress.class: kong
config:
 minute: 100000    # Number of requests allowed per minute
 limit_by: consumer
 policy: local
plugin: rate-limiting