# version: '3.8'
# services:
#   mongo:
#     image: mongo:7
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-auth-data:/data/db

#   auth-service:
#     build: .
#     ports:
#       - "3000:3000"
#     env_file:
#       - ./.env
#     depends_on:
#       - mongo
#     environment:
#       - MONGODB_URI=mongodb://mongo:27017/auth_db

# volumes:
#   mongo-auth-data: